### ISSUE TITLE
Update Readme with valid deployment steps and add to default CSS minimizing

### ISSUE THREAD

**Issue by pftg** [jetthoughts/jt.github.io#167]

**Comment by mir4a** [comment]
@pftg no need add to default `uncss` task, because it is very heavy and need to be run only before deploy (push to master). Css is already minimizing by sass if you meant this, but `uncss` is needed too, but should run only once at the end of development and before pushing to master. Default tasks using while developing current feature and we don't need to run `uncss` every time dev press `Cmd+S` right?

**Comment by pftg** [comment]
Then we need task which will be for packaging only
