### ISSUE TITLE
Comments counter

### ISSUE THREAD

**Issue by tehhi42** [jetthoughts/jt.github.io#66]
http://minus.com/lbf2bCd485g55K
Compare with design http://minus.com/lOjwCuqvVpIoG

**Comment by mir4a** [comment]
The application will be deployed to: http://jetthoughts-github-io-66-comme.herokuapp.com
Monitor the job status at: http://instapusher.com/projects/jetthoughts-jetthoughts-github-io/jobs/1101

**Comment by mir4a** [comment]
@tehhi42 finally! It works! After link mapping, it has ability to proper counting and saves comment thread!

Pls verify.

**Comment by tehhi42** [comment]
@mir4a I was not able to save comment for this article. http://jetthoughts-github-io-66-comme.herokuapp.com/blog/team/2014/04/17/how-to-learn-ruby.html

**Comment by mir4a** [comment]
@tehhi42 have you tried to login? http://jetthoughts-github-io-66-comme.herokuapp.com/blog/team/2014/04/17/how-to-learn-ruby.html#comment-1428221873

**Comment by tehhi42** [comment]
@mir4a now it works. http://screencast.com/t/oRCkkOkrVaIm But there is still 0 comments. http://screencast.com/t/mnqVRrzNO

**Comment by mir4a** [comment]
@tehhi42 I see that. I'ts because we deployed to different addresses, and disqus looking for www.jetthoughts.com. That's why I added migration links map yday, it helps disqus count old comments. It means that old comment threads are visible now (http://www.jetthoughts.com/blog/magic/2010/12/22/allow-multiple-access-control-requests-for-rails.html#disqus_thread), but if you want to check a NEW comments on deployed address I have to add deployed addresses to migration links map.

So next step is to test my changes on production and then we'll see how they're successful was or not. I propose to merge this for now and check back to production. @pftg what do you think?

**Comment by pftg** [comment]
@mir4a :+1: yes, please merge and deploy

**Comment by pftg** [comment]
@mir4a but before that show me the PR :cry:

**Comment by mir4a** [comment]
@pftg pr goes here #113
